# SPDX-FileCopyrightText: 2026 GARDENA GmbH
#
# SPDX-License-Identifier: GPL-3.0-or-later

repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.3
  hooks:
    # Run the linter.
    - id: ruff
      args: [ "--select=I", "--fix" ]
    # Run the formatter.
    - id: ruff-format
