
trigger:
- "*"

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  fetchDepth: 0

- script: | 
    set -eu -o pipefail

    sudo apt update
    sudo apt install -qq -y libxml2-utils
  displayName: 'Install dependencies'

- script: wget https://www.openmobilealliance.org/tech/profiles/LWM2M-v1_1.xsd
  displayName: 'Get XSD schema for IPSO definitions v1.1'
  workingDirectory: /tmp

- script: xmllint --noout --schema /tmp/LWM2M-v1_1.xsd *.xml
  displayName: 'Validate IPSO definitions v1.1'
  workingDirectory: definitions

- script: ./check_changed_ipso_definitions.sh origin/main HEAD
  displayName: 'Check definition not changed'
  workingDirectory: scripts
  condition: and(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['System.PullRequest.TargetBranch'], 'refs/heads/main'))

- script: |
    set -eu -o pipefail

    # Check script first
    python3 -m venv .venv && . .venv/bin/activate
    pip install pre-commit
    pre-commit run --all-files
    # Run script
    ./check_definition_files.py ../definitions
  displayName: 'Sanity Checks for Specification Files'
  workingDirectory: scripts
